volumes:
  postgres:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  vue-app:
    build:
      context: ./frontend
    container_name: vue-app
    ports:
      - "8080:8080" # Mapeia a porta 8080 do container para a porta 8080 da máquina host
    volumes:
      - ./frontend:/app # Para permitir o desenvolvimento em tempo real, sem a necessidade de reconstruir a imagem toda vez
    environment:
      - NODE_ENV=development # Define o ambiente como desenvolvimento
    networks:
      - frontend
  laravel-app:
    build:
      context: ./backend
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/
    networks:
      - frontend
      - backend
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    volumes:
      - /database-volume/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend
